{
    "name": "Odoo SaaS Manager",
    "summary": "Manage SaaS tenants, plans, subscriptions, and payments for multi-database Odoo hosting.",
    "version": "19.0.1.3.0",
    "category": "Administration",
    "author": "Emad Khadra",
    "license": "LGPL-3",
    "depends": ["base", "mail", "account"],
    "data": [
        "security/saas_security.xml",
        "security/ir.model.access.csv",
        "data/saas_sequence.xml",
        "data/saas_cron.xml",
        "views/saas_dashboard_views.xml",
        "views/saas_plan_views.xml",
        "views/saas_tenant_views.xml",
        "views/saas_subscription_views.xml",
        "views/saas_payment_views.xml",
        "views/saas_provisioning_log_views.xml",
        "views/saas_onboarding_import_wizard_views.xml",
        "views/saas_menu.xml",
        "views/res_config_settings_views.xml",
    ],
    "demo": [
        "demo/saas_plan_demo.xml",
    ],
    "application": True,
    "installable": True,
}
